# System
COMMON_HOSTNAME: '{{ instance.domain }}'
COMMON_ENVIRONMENT: opencraft
COMMON_DEPLOYMENT: '{{ instance.internal_lms_domain }}'

# HTTP authentication
COMMON_ENABLE_BASIC_AUTH: true
COMMON_HTPASSWD_USER: '{{ instance.http_auth_user }}'
COMMON_HTPASSWD_PASS: '{{ instance.http_auth_pass }}'

# edxapp
EDXAPP_PLATFORM_NAME: "{{ instance.name }}"
EDXAPP_SITE_NAME: '{{ instance.domain }}'
EDXAPP_LMS_NGINX_PORT: 80
EDXAPP_LMS_SSL_NGINX_PORT: 443
EDXAPP_LMS_BASE_SCHEME: 'https'
EDXAPP_LMS_SITE_NAME: '{{ instance.domain }}'
EDXAPP_LMS_BASE: '{{ instance.domain }}'

EDXAPP_LMS_PREVIEW_NGINX_PORT: 80
EDXAPP_PREVIEW_LMS_BASE: '{{ instance.lms_preview_domain }}'

EDXAPP_CMS_NGINX_PORT: 80
EDXAPP_CMS_SSL_NGINX_PORT: 443
EDXAPP_CMS_SITE_NAME: '{{ instance.studio_domain }}'
EDXAPP_CMS_BASE: '{{ instance.studio_domain }}'
CMS_HOSTNAME: '{{ instance.studio_domain_nginx_regex }}'

# Set this to a string such as ".myinstance.org" to enable session sharing between LMS and the Studio.
# We cannot do this on OC IM for security reasons (we don't want different *instances* to share cookies).
EDXAPP_SESSION_COOKIE_DOMAIN: ''

# Nginx
NGINX_SET_X_FORWARDED_HEADERS: false

# SSL is handled on the load balancer, and the appservers are HTTP only.
NGINX_ENABLE_SSL: false
NGINX_REDIRECT_TO_HTTPS: false

# Nginx redirects (optional)
# This example redirects non-www to www version of myinstance.org.
# nginx_redirects:
#   no_www_to_www:
#     server_names: ['myinstance.org']
#     redirect_destination: 'https://www.myinstance.org'
#     ssl: true

# Forum environment settings
FORUM_RACK_ENV: 'production'
FORUM_SINATRA_ENV: 'production'

# Emails
EDXAPP_CONTACT_EMAIL: '{{ appserver.email }}'
EDXAPP_TECH_SUPPORT_EMAIL: '{{ appserver.email }}'
EDXAPP_BUGS_EMAIL: '{{ appserver.email }}'
EDXAPP_FEEDBACK_SUBMISSION_EMAIL: '{{ appserver.email }}'
EDXAPP_DEFAULT_FROM_EMAIL: '{{ appserver.email }}'
EDXAPP_DEFAULT_FEEDBACK_EMAIL: '{{ appserver.email }}'
EDXAPP_SERVER_EMAIL: '{{ appserver.email }}'
EDXAPP_BULK_EMAIL_DEFAULT_FROM_EMAIL: '{{ appserver.email }}'
ECOMMERCE_OSCAR_FROM_EMAIL: '{{ appserver.email }}'

{% if smtp_relay_settings %}
# Do not change the email settings below - use POSTFIX_QUEUE_EXTERNAL_SMTP_HOST etc. instead
{% endif %}
EDXAPP_EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend'
EDXAPP_EMAIL_HOST: 'localhost'
EDXAPP_EMAIL_PORT: 25
EDXAPP_EMAIL_HOST_USER: ''
EDXAPP_EMAIL_HOST_PASSWORD: ''
EDXAPP_EMAIL_USE_TLS: false

# Security updates
COMMON_SECURITY_UPDATES: true
SECURITY_UNATTENDED_UPGRADES: true
SECURITY_UPDATE_ALL_PACKAGES: false
SECURITY_UPGRADE_ON_ANSIBLE: true

# OAuth
EDXAPP_OAUTH_ENFORCE_SECURE: false

# Set YouTube API key to null to avoid YouTube XHR errors.
# Can be overridden in extra settings with a valid API key.
EDXAPP_YOUTUBE_API_KEY: !!null

# Set analytics url to an empty string to hide links to Insights on instructor dashboard.
# For installations that include analytics, this should be set to the base Insights URL.
EDXAPP_ANALYTICS_DASHBOARD_URL: ''

# Notifier (forum digest notifications)
NOTIFIER_DIGEST_TASK_INTERVAL: '1440'  # 1440 minutes == 24 hours
NOTIFIER_DIGEST_EMAIL_SENDER: '{{ appserver.email }}'
NOTIFIER_LMS_URL_BASE: 'https://{{ instance.domain }}'
NOTIFIER_LOGO_IMAGE_URL: 'https://{{ instance.domain }}/static/images/logo.png'

{% if smtp_relay_settings %}
# Do not change the email settings below - use POSTFIX_QUEUE_EXTERNAL_SMTP_HOST etc. instead
{% endif %}
NOTIFIER_EMAIL_BACKEND: 'smtp'
NOTIFIER_EMAIL_HOST: 'localhost'
NOTIFIER_EMAIL_PORT: 25
NOTIFIER_EMAIL_USER: ''
NOTIFIER_EMAIL_PASS: ''
NOTIFIER_EMAIL_USE_TLS: false

# Repositories URLs
edx_ansible_source_repo: '{{ appserver.configuration_source_repo_url }}'
edx_platform_repo: '{{ appserver.edx_platform_repository_url }}'

# Pin down dependencies to specific (known to be compatible) commits.
edx_platform_version: '{{ appserver.edx_platform_commit }}'
configuration_version: '{{ appserver.configuration_version }}'
forum_version: '{{ appserver.openedx_release }}'
xqueue_version: '{{ appserver.openedx_release }}'
certs_version: '{{ appserver.openedx_release }}'
NOTIFIER_VERSION: '{{ appserver.openedx_release }}'
ANALYTICS_API_VERSION: '{{ appserver.openedx_release }}'
INSIGHTS_VERSION: '{{ appserver.openedx_release }}'
ECOMMERCE_VERSION: '{{ appserver.openedx_release }}'

# Misc
EDXAPP_LANG: 'en_US.UTF-8'
EDXAPP_TIME_ZONE: 'UTC'

# Available as ENV_TOKENS in the django setting files.
EDXAPP_ENV_EXTRA:
  LANGUAGE_CODE: 'en'

# Features
EDXAPP_FEATURES:
  ALLOW_ALL_ADVANCED_COMPONENTS: true
  AUTH_USE_OPENID: false
  CERTIFICATES_ENABLED: true
  CERTIFICATES_HTML_VIEW: true
  ENABLE_COMBINED_LOGIN_REGISTRATION: true
  ENABLE_DISCUSSION_SERVICE: true
  ENABLE_DISCUSSION_HOME_PANEL: true
  ENABLE_DISCUSSION_EMAIL_DIGEST: true
  ENABLE_DJANGO_ADMIN_SITE: true
  ENABLE_INSTRUCTOR_ANALYTICS: true
  ENABLE_INSTRUCTOR_EMAIL: true
  ENABLE_OAUTH2_PROVIDER: true
  ENABLE_PEARSON_HACK_TEST: false
  ENABLE_GRADE_DOWNLOADS: true
  ENABLE_THIRD_PARTY_AUTH: true
  ENABLE_XBLOCK_VIEW_ENDPOINT: true
  PREVIEW_LMS_BASE: '{{ instance.lms_preview_domain }}'
  REQUIRE_COURSE_EMAIL_AUTH: false
  USE_MICROSITES: false
  PREVENT_CONCURRENT_LOGINS: false
  # These are not part of the standard install:
  # CUSTOM_COURSES_EDX: true
  # ENABLE_LTI_PROVIDER: true
  # ENABLE_PREREQUISITE_COURSES: true
  # ENABLE_PROCTORED_EXAMS: true
  # INDIVIDUAL_DUE_DATES: true
  # MILESTONES_APP: true

{% with github_username_list=appserver.github_admin_username_list %}
{% if github_username_list %}# Users
COMMON_USER_INFO:{% for github_username in github_username_list %}
  - name: {{ github_username }}
    github: true
    type: admin{% endfor %}
{% endif %}
{% endwith %}

# Workers
EDXAPP_WORKER_DEFAULT_STOPWAITSECS: 1200

# Monitoring
COMMON_ENABLE_NEWRELIC: {% if newrelic_license_key %}true{% else %}false{% endif %}
COMMON_ENABLE_NEWRELIC_APP: {% if newrelic_license_key %}true{% else %}false{% endif %}
NEWRELIC_LICENSE_KEY: '{{ newrelic_license_key|default:"" }}'

{% with smtp_relay_settings=appserver.smtp_relay_settings %}
{% if smtp_relay_settings %}# Relay email through external SMTP provider.
POSTFIX_QUEUE_EXTERNAL_SMTP_HOST: '{{ smtp_relay_settings.host }}'
POSTFIX_QUEUE_EXTERNAL_SMTP_PORT: '{{ smtp_relay_settings.port }}'
POSTFIX_QUEUE_EXTERNAL_SMTP_USER: '{{ smtp_relay_settings.username }}'
POSTFIX_QUEUE_EXTERNAL_SMTP_PASSWORD: '{{ smtp_relay_settings.password }}'
{% if smtp_relay_settings.rewritten_address %}
# The following two settings ensure that original From address is copied into the Reply-To header,
# after which the original From address is replaced with an address constructed from instance domain
# and the INSTANCE_SMTP_RELAY_SENDER_DOMAIN setting, for example: lms.myinstance.org@opencraft.hosting.
POSTFIX_QUEUE_HEADER_CHECKS: '/^From:(.*)$/   PREPEND Reply-To:$1'
POSTFIX_QUEUE_SENDER_CANONICAL_MAPS: '{{ smtp_relay_settings.source_address }}  {{ smtp_relay_settings.rewritten_address }}'
{% endif %}
{% endif %}
{% endwith %}

# Ecommerce
SANDBOX_ENABLE_ECOMMERCE: false  # set to true to enable ecommerce
ECOMMERCE_ECOMMERCE_URL_ROOT: 'https://{{ instance.domain }}:18130'
ECOMMERCE_SUPPORT_URL: 'https://{{ instance.domain }}'
ECOMMERCE_LMS_URL_ROOT: '{{ instance.domain }}'
ECOMMERCE_PLATFORM_NAME: "{{ EDXAPP_PLATFORM_NAME }}"
# Set your own ECOMMERCE_PAYMENT_PROCESSOR_CONFIG, or update the variables for the appropriate processor:
# * CyberSource
ECOMMERCE_CYBERSOURCE_PROFILE_ID: 'SET-ME-PLEASE'
ECOMMERCE_CYBERSOURCE_MERCHANT_ID: 'SET-ME-PLEASE'
ECOMMERCE_CYBERSOURCE_ACCESS_KEY: 'SET-ME-PLEASE'
ECOMMERCE_CYBERSOURCE_SECRET_KEY: 'SET-ME-PLEASE'
ECOMMERCE_CYBERSOURCE_TRANSACTION_KEY: 'SET-ME-PLEASE'
ECOMMERCE_CYBERSOURCE_PAYMENT_PAGE_URL: 'https://set-me-please'
ECOMMERCE_CYBERSOURCE_RECEIPT_PAGE_URL: '{{ ECOMMERCE_LMS_URL_ROOT }}/commerce/checkout/receipt/'
ECOMMERCE_CYBERSOURCE_CANCEL_PAGE_URL: '{{ ECOMMERCE_LMS_URL_ROOT }}/commerce/checkout/cancel/'
ECOMMERCE_CYBERSOURCE_SOAP_API_URL: 'https://set-me-please'
# * PayPal
ECOMMERCE_PAYPAL_MODE: 'SET-ME-PLEASE'
ECOMMERCE_PAYPAL_CLIENT_ID: 'SET-ME-PLEASE'
ECOMMERCE_PAYPAL_CLIENT_SECRET: 'SET-ME-PLEASE'
ECOMMERCE_PAYPAL_RECEIPT_URL: '{{ ECOMMERCE_LMS_URL_ROOT }}/commerce/checkout/receipt/'
ECOMMERCE_PAYPAL_CANCEL_URL: '{{ ECOMMERCE_LMS_URL_ROOT }}/commerce/checkout/cancel/'
ECOMMERCE_PAYPAL_ERROR_URL: '{{ ECOMMERCE_LMS_URL_ROOT }}/commerce/checkout/error/'

# Comprehensive theming
# EDXAPP_ENABLE_COMPREHENSIVE_THEMING: true
# EDXAPP_COMPREHENSIVE_THEME_DIRS:
#   - '/edx/app/edxapp/themes'
# EDXAPP_DEFAULT_SITE_THEME: 'my-theme-name'
# edxapp_theme_name: '{{ EDXAPP_DEFAULT_SITE_THEME }}'
# edxapp_theme_source_repo: 'https://github.com/open-craft/my-comprehensive-theme.git'
# edxapp_theme_version: 'master'

# Custom requirements.
# Include only if there are custom requirements, e.g.
# EDXAPP_EXTRA_REQUIREMENTS:
#   - name: git+https://github.com/open-craft/xblock-leaderboard.git@61f831ba9b1ff899b40df3ea13111f6ffdd44859#egg=xblock-leaderboard
